name: 测试-py3.11
on:
  push:
    branches: [ slave ]
  pull_request:
    branches: [ slave ]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.11.1
      - name: unittest
        run: python ut.py
